"""Auditable vocabulary used by the supplement NLP pipeline."""

SUPPLEMENT_LIST = [
    "5-HTP",
    "ashwagandha",
    "beta-alanine",
    "caffeine",
    "calcium",
    "choline",
    "coenzyme Q10",
    "creatine",
    "curcumin",
    "electrolytes",
    "fish oil",
    "folate",
    "GABA",
    "ginkgo biloba",
    "ginseng",
    "glycine",
    "iron",
    "L-citrulline",
    "L-theanine",
    "lion's mane",
    "magnesium",
    "melatonin",
    "multivitamin",
    "NAC",
    "niacin",
    "omega-3",
    "potassium",
    "probiotics",
    "protein powder",
    "rhodiola rosea",
    "taurine",
    "turmeric",
    "vitamin A",
    "vitamin B12",
    "vitamin C",
    "vitamin D",
    "vitamin E",
    "whey protein",
    "zinc",
]

SUPPLEMENT_SYNONYMS = {
    "5-HTP": ["5 htp", "5-hydroxytryptophan"],
    "coenzyme Q10": ["coq10", "co-q10"],
    "creatine": ["creatine monohydrate"],
    "fish oil": ["fish oils"],
    "folate": ["folic acid"],
    "L-citrulline": ["citrulline", "citrulline malate"],
    "L-theanine": ["theanine", "l theanine"],
    "lion's mane": ["lions mane", "lion’s mane", "hericium erinaceus"],
    "magnesium": ["magnesium glycinate", "magnesium citrate", "magnesium threonate"],
    "NAC": ["n-acetylcysteine", "n acetyl cysteine"],
    "omega-3": ["omega 3", "omega-3s", "EPA DHA"],
    "protein powder": ["protein powders"],
    "rhodiola rosea": ["rhodiola"],
    "turmeric": ["turmeric extract"],
    "vitamin B12": ["b12", "cobalamin"],
    "vitamin C": ["ascorbic acid"],
    "vitamin D": ["d3", "vitamin d3", "cholecalciferol"],
    "whey protein": ["whey isolate", "whey concentrate"],
}

ASPECT_TERMS = {
    "effectiveness_pos": ["effective", "worked", "helped", "benefit", "improvement"],
    "effectiveness_neg": ["ineffective", "didn't work", "no effect", "useless", "placebo"],
    "side_effects_pos": ["no side effects", "well tolerated"],
    "side_effects_neg": ["side effect", "headache", "nausea", "dizziness", "rash"],
    "sleep_pos": ["better sleep", "slept well", "restful", "insomnia"],
    "sleep_neg": ["worse sleep", "insomnia", "nightmare", "restless"],
    "energy_pos": ["more energy", "energized", "alert", "fatigue", "tiredness", "lethargy"],
    "energy_neg": ["fatigue", "tired", "lethargy", "crash", "jittery"],
    "mood_pos": ["better mood", "calm", "relaxed", "anxiety", "stress", "depression"],
    "mood_neg": ["anxiety", "panic", "irritable", "depression", "stress"],
    "cognition_pos": ["focus", "concentration", "memory", "clarity", "brain fog"],
    "cognition_neg": ["brain fog", "confusion", "forgetful", "poor focus"],
    "cost_pos": ["affordable", "good value", "worth the money"],
    "cost_neg": ["expensive", "overpriced", "waste of money"],
    "physical_performance_pos": ["strength", "endurance", "recovery", "performance"],
    "physical_performance_neg": ["weakness", "poor recovery", "reduced performance"],
    "appetite_pos": ["healthy appetite", "appetite control"],
    "appetite_neg": ["loss of appetite", "increased appetite"],
    "libido_pos": ["higher libido", "improved libido"],
    "libido_neg": ["lower libido", "reduced libido"],
    "skin_hair_nails_pos": ["clear skin", "hair growth", "stronger nails", "acne"],
    "skin_hair_nails_neg": ["acne", "hair loss", "brittle nails", "dry skin"],
    "digestion_pos": ["better digestion", "regular", "bloat", "constipation", "diarrhea"],
    "digestion_neg": ["bloat", "constipation", "diarrhea", "stomach pain", "indigestion"],
    "onset_duration_pos": ["fast acting", "long lasting", "kicked in"],
    "onset_duration_neg": ["wore off", "short lived", "slow to work"],
}

INTENT_LABELS = ["experience", "question", "informational", "promotional", "other"]

